# Generated by Django 5.2 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_status'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='labels', to='cards.card'),
        ),
    ]
